---
- hosts: all
  gather_facts: False

  tasks:
    - name: Generate interfaces config file
      template:
        src: ../templates/interfaces.j2
        dest: /etc/network/interfaces
        backup: yes
      notify: reload networking
