---
- hosts: cum-1
  gather_facts: True

  tasks:
    - setup:
        filter: ansible_*
      register: facts
    - debug:
        var: facts


    - name: ADD INTERFACE DESCRIPTION
      nclu:
        commands:
          - add interface eth0 alias //--VBOX_MGMT--//
        commit: true
      register: result_1
    - debug:
        var: result_1
