---
- hosts: all
  gather_facts: False

  tasks:
    - name: enable quagga
      template:
        src: ../templates/quagga.j2
        dest: /etc/frr/daemons
        backup: no
      notify: reload frr

    - name: routing configuration
      template:
        src: ../templates/routing.j2
        dest: /etc/frr//frr.conf
        backup: yes
      notify: reload frr

  handlers:
    - name: reload frr
      service:
        name: frr
        state: reloaded
